[package]
name = "ws2812-spi"
version = "0.1.0"
authors = ["David Sawatzke <david-sawatzke@users.noreply.github.com>"]
edition = "2018"

[dependencies]
nb = "0.1.1"
smart-leds-trait = {git = "https://github.com/smart-leds-rs/smart-leds-trait"}
embedded-hal = "0.2.1"

[features]
mosi_idle_high = []
